### ISSUE TITLE
NaN value in JSON output

### ISSUE THREAD

**Issue by victorskl** [MultiQC/MultiQC#1509]
### Description of bug

There seem to be `NaN` as value when choose to dump in JSON format i.e. `--data-format json`. This is of course invalid as JSON value. Please see attached screenshot. And error condition for use case such as when trying to insert MultiQC data straight into MySQL table as JSON data type. Report itself render no issue. I can also report that this happen on SnpEff toolbox / plot data.

I also note that, in Python `json.dumps` [allowed NaN by default](https://stackoverflow.com/questions/6601812/sending-nan-in-json). For better, it should `allow_nan=False` to conform with JSON format, I suppose. 

We have post-processing step for MultiQC data ingestion. Do you recommend setting `NaN` to `null` if we handle during processing? 

Our MultiQC version is `1.10.dev0`.

Thanks

![image](https://user-images.githubusercontent.com/4586509/128121593-035ebf6a-f0a4-41da-bdfb-89750681fa88.png)

**Comment by cmatKhan** [comment]
```
library(TidyMultiqc)
library(here)

df = load_multiqc(here("data/multiqc_output.json"))
```

```
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                  "mapped_failed_pct": NaN,                 "paired in
                     (right here) ------^
```

What did you do? replace NaN with some known nonsense number in the JSON?

**Comment by brainstorm** [comment]
I wonder if we could somehow lure @pcingola (main dev of snpEff AFAICT) to drop the use of `NaN` in snpEff and instead use a very large number to stay within the designated schema type:

https://github.com/pcingola/SnpEff/search?p=1&q=NaN

That'd solve the issue(s) we are seeing here with Python's JSON serialization where the data type for several fields flips from `Double` to something that JSON parsers do not accept as `Double` (because it isn't).

Please note that turning `NaN` into a string is not a good option either for the aforementioned reasons ;)

/cc @reisingerf @ohofmann @andrewpatto

**Comment by ewels** [comment]
> Do you recommend setting `NaN` to `null` if we handle during processing?

I guess that this is the best solution.. The Stack Overflow post you linked to has a comment saying that the `simplejson` package can do this conversion, instead of just falling over with a `ValueError`.

If it's only a limited number of modules doing this (just SnpEff?) then the easiest solution would probably be to get the module code to replace `NaN` with `None`, which will then be serialised to `null` in the JSON.

**Comment by multimeric** [comment]
It's not just SnpEff. I'm getting error reports (https://github.com/multimeric/TidyMultiqc/issues/9 and https://github.com/multimeric/TidyMultiqc/issues/6), which suggest that the following fields are often NaN:
*` mapped_failed_pct`
* `properly paired_failed_pct`
* `properly paired_passed_pct`
* `singletons_failed_pct`
* `singletons_passed_pct`

I think these are all from the `samtools` module.

I'd like to +1 the suggestion of changing these to `null`. I think there's always going to be a risk that modules output NaN (intentionally or otherwise), but we never want invalid JSON to be output.

**Comment by ewels** [comment]
Ok, thanks @multimeric. This is best done within the general function that saves JSON outputs then I think. Then it will apply for all modules.

**Comment by loukesio** [comment]
Hello all, 
Have you found a solution in the meantime, running the 
```
library(TidyMultiqc)
library(here)

df = load_multiqc(here("data/multiqc_output.json"))
```

i am still getting the same error as @ewels

**Comment by multimeric** [comment]
If your issue is with `TidyMultiqc`, refer to the issue here: https://github.com/multimeric/TidyMultiqc/issues/9. I have one proposed solution, but it hasn't been confirmed to work.

**Comment by Emiller88** [comment]
https://stackoverflow.com/questions/6601812/sending-nan-in-json Just ran into this. Might get cleaned up in #1790 anyways 🙃

**Comment by vladsavelyev** [comment]
Too bad the standard JSON module doesn't take a custom handler for that :( I didn't want to add simplejson, so just went with a hack: https://github.com/MultiQC/MultiQC/pull/2432

**Comment by ewels** [comment]
Thank you everyone for your patience! Hopefully this is now finally fixed..

![image](https://github.com/MultiQC/MultiQC/assets/465550/21150ab6-4d29-4c37-aa99-e777869b9416)
