### ISSUE TITLE
Sample rename does not work as expected

### ISSUE THREAD

**Issue by jd3234** [MultiQC/MultiQC#1702]
### Description of bug

Hi,
I am trying to do bulk renaming of samples via command line.  Here is the example of my mapping file

|id	         |new name|
|---------- |----------- |  
|45007	 |13Z0**45031**DH02_leaf_replicate_1 | 
|**45031**|08NR063DH01_leaf_replicate_1 | 

The replication of the ID 45031 in the the new name (bold) is causing the first sample to be combination of the two new names: `13Z008NR063DH01_leaf_replicate_1DH02_leaf_replicate_1` .

I tested to use a config file with `sample_names_replace_complete: True` or `sample_names_replace_exact: True` but that did not help. Is there another way change this behaviour or am I doing something wrong?

### File that triggers the error

[MultiQC.zip](https://github.com/ewels/MultiQC/files/8879679/MultiQC.zip)

zip file contains two FeatureCount Summary files and the sample mapping file.

### MultiQC Error log

```bash
multiqc --sample-names mapping.faulty 45007.fc.tsv.summary 45031.fc.tsv.summary

  /// MultiQC 🔍 | v1.12

|           multiqc | Report title: QC: RNAseq mapping and feature count
|           multiqc | Search path : /mnt/scratch/janina/RNA_MULTIQC/45007.fc.tsv.summary
|           multiqc | Search path : /mnt/scratch/janina/RNA_MULTIQC/45031.fc.tsv.summary
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2  
|    feature_counts | Found 2 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete

```

**Comment by cwarden45** [comment]
I was able to re-name selected samples by using a similar format, with the following differences:

- I used `--replace-names` instead of `--sample-names` (with MultiQC version _v1.13_)
- I did not define a header in the tab-delimited text file, with format otherwise similar to what you described.

I hope that might help!

**Comment by ewels** [comment]
Thanks @cwarden45 ! That feature is slightly different, see the [docs](https://multiqc.info/docs/#sample-name-replacement):

> Occasionally, when you run MultiQC you may know that you want to change the resulting sample names at run time. You can do this using the `--replace-names` option, which allows you to change sample names during report creation.
> **Unlike `--sample-names`, the original names never make it through to the report.**

This approach would work as it's done at run time, whereas `--sample-names` relies on javascript in the browser. But yeah, depending on what @jd3234 needs that might be the best solution here.

@jd3234 it sounds like you've come across a bit of an edge case here, it's been a while since I looked at this code but I'd hope it should be fixable.

**Comment by cwarden45** [comment]
Thank you very much - I think that I understand.

I ran MultiQC with the following command:

```
RENAME=rename.txt
...
multiqc --replace-names $RENAME $FOLDER1 $FOLDER2
```

I am learning more, but I did not realize that this was being run from the browser (if I understand correctly).

Thank you again for clarifying!  I will work on not being a distraction for a different use context.

**Comment by ewels** [comment]
No please continue to be a distraction! I appreciate the help in responding to issues, apologies if I came across in a negative way 😊  Your suggestion is likely the best solution for this at present.

> I did not realize that this was being run from the browser

What you're running, `--replace-names`, is not being run in the browser. That is being run in the Python runtime by MultiQC.

When you use `--sample-names` all that happens is that the sample renaming box in the toolbar on the right of the report is prefilled with a button. So this option does everything with JavaScript.
