### ISSUE TITLE
Replace plotting library

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#1789]
HighCharts has served MultiQC very well, but it's time to move to something else. Key issues are:

- Limited numbers of plot types
- Requirement to write back-end plotting code in matplotlib manually to mimic appearance of front-end plots

Any new plotting library:

- Must have a permissive licence (eg. MIT)
- Should have a native Python implementation
- Should be able to generate static plots directly from the Python run time
- Should have a good degree of theme customisation options
- Should be extensible in the javascript front-end (eg. for highlight / hide / renaming tools)
- Should be compatible with MultiQC's efforts to compress data for small report sizes
- Work equally well in Jupyter notebooks with interactive use

The current top runner is [Plotly](https://plotly.com/), though [Vega-Altair](https://altair-viz.github.io/) could also be a good option (especially due to the open Vega grammar being good for reuse).

**Comment by multimeric** [comment]
Agreed with the two contenders. Plotly has the advantage of offering a very large library of plots, including some bioinformatics specific things (dash-bio perhaps?), and having an enormous user base. On the other hand, Vega is an open standard. One advantage of this is that it's not dependent on the whims of Plotly, who have been a bit weird about the license for the library. This also means that plot config is standardised and machine readable, so I can imagine a scenario where we export the plot config and plot data from MultiQC, and provide it to a third party renderer so that it integrates into someone's existing dashboard, instead of needing to embed HTML. This also allows us to swap out our own rendering library from Altair to something else that supports Vega in the future, without breaking everything.

**Comment by ewels** [comment]
> Plotly, who have been a bit weird about the license for the library.

Ah really? I wasn't aware of this. Could you elaborate?

**Comment by multimeric** [comment]
Sorry I was misremembering. It wasn't the license (which was always MIT), but rather the way that they uploaded your plots to their online service by default (or something like that). It's briefly explained here:
https://medium.com/plotly/plotly-py-4-0-is-here-offline-only-express-first-displayable-anywhere-fc444e5659ee.

These days they're better about delineating the commercial from open source parts, however.

**Comment by ewels** [comment]
If we do go for Plotly and also start using React then this looks like a pretty nice setup: https://plotly.com/javascript/react/

**Comment by vladsavelyev** [comment]
Plotly is a great choice. Glad that there is no more confusion about online/offline and commercial/free versions as it was in the past. Also nice that plotly-express is bundled with the main library.

Regarding react-plotly, looks like it mostly provides shorthands to avoid some extra boilerplate lines in JavaScript? E.g. this React code

```html
import Plot from 'react-plotly.js';

class App extends React.Component {
  render() {
    return (
      <Plot
        data={[
          {
            x: [1, 2, 3],
            y: [2, 6, 3],
          },
          {type: 'bar'}
        ]}
      />
    );
  }
}
```

Could be replicated in Svelte with a couple of `div`s:

```svelte
<script src="https://cdn.plot.ly/plotly-latest.min.js" type="text/javascript"></script>
<script>
  export let data = {[{
      x: [1, 2, 3],
      y: [2, 6, 3],
    },
    {type: 'bar'}
  ]};
  onMount(() => {
    let plotDiv = document.getElementById('plotDiv');				
    let Plot = new Plotly.newPlot(plotDiv, data); 
  });      
</script>

<div id="plotly">
  <div id="plotDiv"></div>
</div>
```

(Though I'm don't yet sure how much React and Svelte would benefit a standalone MultiQC report - but that's another discussion!)
