### ISSUE TITLE
Qualimap RNAseq locale parsing error

### ISSUE THREAD

**Issue by fspecque** [MultiQC/MultiQC#1870]
### Description of bug

Hello,

Thanks for this great tool. I've noticed a bug which seems to arise from a parsing error of qualimap RNAseq output. If I understood correctly, MultiQC parses the `rnaseq_qc_results.txt` from qualimap rnaseq analysis. But the authors of qualimap have separated the hundreds by a space, thus the counts displayed in MultiQC's report based on qualimap RNAseq output are incorrect. I guess the regex that is being used stops at blanks.

Example of qualimap RNAseq output:
```shell
>>>>>>> Reads genomic origin

    exonic =  1 233 088 (38,7%)
    intronic = 1 119 695 (35,14%)
    intergenic = 833 548 (26,16%)
    overlapping exon = 61 165 (1,92%)
```
Numbers reported by MultiQC:
![screenshot](https://user-images.githubusercontent.com/41961194/220677234-f4bfface-c06a-4e63-a5fc-e0eef368c6e9.png)

The MultiQC version I use is `1.14`, installed with miniconda.
> Note that the `genome_results.txt` from qualimap bamQC module separates hundreds with commas.

Best,
Florian

### File that triggers the error

[rnaseq_qc_results.txt](https://github.com/ewels/MultiQC/files/10805825/rnaseq_qc_results.txt)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.14

|           multiqc | Report title: MultiQC report for 10 samples (qualimap rnaseq outputs)
|           multiqc | Prepending directory to sample names
|           multiqc | Search path : /home/flospe/Documents/projects/EMTSens/test_10_samples/qualimap_outputs/star_out
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1058/1058  
|          qualimap | Found 30 RNASeq reports
|           multiqc | Compressing plot data
|           multiqc | Report      : MultiQC-report-for-10-samples-qualimap-rnaseq-outputs_multiqc_report.html
|           multiqc | Data        : MultiQC-report-for-10-samples-qualimap-rnaseq-outputs_multiqc_report_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by fspecque** [comment]
After further inspection, it is not a regular space, it a no-break space (unicode: U+00A0)

qualimap version: `2.2.1`

**Comment by ewels** [comment]
Oof, I guess that this is due to a Java locale issue and not really the authors of Qualimap.

Regexes need updating to allow spaces:

https://github.com/ewels/MultiQC/blob/bad886aaf2783fa753a48764000b63457282d4c3/multiqc/modules/qualimap/QM_RNASeq.py#L20-L30

Instead of `[\d,]` need `[\d, ]` (not sure if anything special is needed for the non-breaking space). Then need to strip the spaces afterwards for proper Python float handling.

Looks like we already have support for sorting out `.` thousands separators: 

https://github.com/ewels/MultiQC/blob/bad886aaf2783fa753a48764000b63457282d4c3/multiqc/modules/qualimap/QM_RNASeq.py#L44-L49

These Java locale issues are some of my least favourite in the MultiQC code base!

**Comment by vladsavelyev** [comment]
Fixed in https://github.com/MultiQC/MultiQC/pull/2282
