### ISSUE TITLE
Set up unit testing

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2046]
When we go through refactoring modules for v2.0, take the opportunity to also set up a proper unit testing framework.

Can dump more ideas here, but for example:

* For each module, run a core set of tests:
    * On init, are mandatory variables set
    * On parse + ignore, does it return an exception because no data
    * ...

We can keep the main integration test of running MultiQC on everything, but a bunch of the additional tests that we currently have in the CI can almost certainly be better done as unit tests.

We also have various other sporadic mini-test scripts etc all over the place, so can consolidate those.

Ideas for future work as part of the initial setup:

- [x] Write new page about testing for the docs, with examples
- [x] Have some bespoke module-level function tests for a couple of modules
- [x] Look more into snapshot results for module parsing test data
- [x] Try and bulk up coverage on some core files (interactive.py, write_results.py etc)

After this we can consider the issue complete, and try to continue adding test coverage whenever we work on any file or fix any bugs.

**Comment by vladsavelyev** [comment]
Regarding the currently existing integration testing, there are several modules that fail when multiple incompatible inputs are passed (`preseq`, `bclconvert`), and they probably _should_ make MultiQC exit with error code 1. It's not practical at the moment because that would make the integration test `multiqc test_data/modules` always fail, since we have mixture of inputs for those modules in MultiQC_TestData.

So I think it might makes sense to break up those modules into module groups, using the config with `path_filters` in the CI runs.
