### ISSUE TITLE
request: version tags for docker builds

### ISSUE THREAD

**Issue by kelly-sovacool** [MultiQC/MultiQC#2249]
### Description of feature

It would be great to have different tags on docker corresponding to released versions of multiqc to enable reproducibility or rolling back to older versions. It looks like this used to be set up when the container was hosted on dockerhub at `ewels/multiqc` but was lost in the migration to `multiqc/multiqc`.

**Comment by ewels** [comment]
Yup - we had this and will have it at the new address going forward. I wanted to copy over all the old versions retrospectively for the new address, but wasn't able to find an easy way to do this.

I got close, but could only do one architecture at a time - not copying the multi platform arm / intel builds. If anyone knows a way to copy all of these over then I'm happy to give it a try.

**Comment by ewels** [comment]
Ok, I've pulled all of the `ewels/multiqc` tags and pushed them to `multiqc/multiqc`. I ran it with `--platform linux/amd64`.

We've lost the multi-arch (ARM) builds from the releases v1.14 - v1.19, but I figure that most users will be using amd anyway, so it's not such a huge loss. Better to at least have the tags there. Going forward the automation should push out new releases with multi-arch builds again in the future.

Shout if you hit any issues, otherwise I think I've done as much as I can here. Thanks!
