### ISSUE TITLE
Remove "%" and "M" and the extraneous extra characters in General Stats report

### ISSUE THREAD

**Issue by rarthur-eicc** [MultiQC/MultiQC#2389]
### Description of feature

See title. Since 1.20, the extraneous % and "M" in "M seqs" (already labeled M seqs, so the M is redundant) should be taken out if possible. For columns such as "% dups", the data also has "NN %" in it, which is also redundant. When exporting these into Excel/ R, they have some special invisible characters in them that ruin operations beyond the numbers, so "55.1 M" isn't just 55.1<space>M , but something else and regex had to be used. 

Can these be either removed or toggable so that we just get the numbers only like in all prior versions?

**Comment by vladsavelyev** [comment]
Thanks for raising this issue! 

You are probably referring to the "Copy table" button? I didn't realize that the `&nbsp;` character that we use to separate a suffix and the value could cause problems in Excel, but it's a good point, as we don't actually need it - I just added a PR to use CSS instead to guarantee that the cell contents don't wrap in the browser, so now the invisible character or any space won't be copied into the clipboard: https://github.com/MultiQC/MultiQC/pull/2395

Note, however, that the "Copy table" is designed to copy values formatted as-is, and we want them to be rounded and suffixed, as we prefer the report look human-readable. If you want raw values to do some scripted post-processing or do something with the values in Excel, I added another button  "Export as TSV" which is useful for that - it would export the unformatted values, e.g. 1201951 instead of 1.2M, etc: https://github.com/MultiQC/MultiQC/pull/2394

You are correct that some modules duplicated the suffixes like `M` and `%` in the header  - I intend to clean this up eventually.

**Comment by rarthur-eicc** [comment]
I see where you’re coming from. However, from a user standpoint, the way things were in all versions up until 1.20 made sense as well where you have headers with clear labels (%, M Seqs, et cetera), and that did not need to be moved into the table itself. You mention human legibility, most people do read the headers first and understand that the “%” or “M” in “M seqs” applies to all cells going downward, so you have one of those characters in the header versus the new implementation having one in every cell which looks visually cluttered and is overly redundant. I would argue that having “neat” or “clean” looking cells and having all labels / extra characters only in the headers is in fact more “human-readable” and looks better. I do not think you will get a loss of understanding if you don’t see a “M” or “%” next to every single cell. It just seems that this change is unnecessary and does the exact opposite of your intention in making it actually less human-readable and more visually cluttered or “busy” to the eye. If I were reading a chart in a report or in a manuscript (again, this is a scientific tool), I always start with the header and remember units. If things have looked good and clean for years, why change them now?

Again, I do appreciate your response and the implementation of the request, but your responses seem a bit “this is how it is and we’ve decided XYZ” where this is supposed to be a public tool for the scientific world which encourages lots of feedback and the like from the community. I personally find the older versions tabular output to be cleaner and more human-readable than those in 1.20.

Thank you!
