### ISSUE TITLE
v1.22 does not work inside nextflow work directory

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2569]
Urgent bug / regression introduced in today's v1.22 release that I just stumbled across - MultiQC no longer searches within symlinked directories.

This needs fixing and we will need to do a patch release 😢 

Likely related to search refactoring work @vladsavelyev @rhpvorderman

**Comment by vladsavelyev** [comment]
Can you help reproduce?

I re-enabled unit-tests https://github.com/MultiQC/MultiQC/pull/2570 and the symlink search test is passing: https://github.com/MultiQC/test-data/blob/c3952131ec5ae7fc169577027a3c65d5326380ea/unit_tests/test_get_filelist.py#L51-L61

**Comment by rorynolan** [comment]
FWIW I can confirm that `multiqc` can no longer find files for me after the update. This is probably it because I use nextflow which uses a lot of symlinks.

**Comment by rhpvorderman** [comment]
I did a check of the file content searching work but most of it is just copy pastes from the old codebase. I can't find (by naked eye) any changes that would trigger this.

I tested on a symlinked directory: no issues. 

I tested on a symlinked directory inside of a normal directory. No issues. 

I would gladly fix any issues in the code I contributed, but I need to be able to reproduce the error in order to do so.

**Comment by vladsavelyev** [comment]
>  This is probably it because I use nextflow

Right, turns out the original issue Phil had also had to do with running inside nextflow, Phil shared the workflow to reproduce: https://github.com/ewels/nf-test-multiqc

So it's actually not an issue with symlinks, but rather with the nextflow work folder being ignored in the config defaults: https://github.com/MultiQC/MultiQC/blob/main/multiqc/config_defaults.yaml#L124

I'm not really sure why it worked in v1.21 - will check.
